name: Test

on:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ubuntu:24.04
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Build
      run: |
        export DEBIAN_FRONTEND=noninteractive
        apt-get update -qq
        apt-get install -qqy --no-install-recommends \
          ruby-full \
          build-essential \
          zlib1g-dev \
          locales
        echo "en_US UTF-8" > /etc/locale.gen
        locale-gen en_US.UTF-8
        export LANG=en_US.UTF-8
        export LANGUAGE=en_US:en
        export LC_ALL=en_US.UTF-8
        bundle3.2
        jekyll build

    - uses: actions/upload-artifact@v4
      with:
        name: rendered-site
        path: "_site/"

  link:
    runs-on: ubuntu-latest
    needs: build # make sure the artifacts are uploaded first
    permissions:
        contents: write # for commenting on your commit
        pull-requests: write # for commenting on your pr
    steps:
      - uses: beni69/artifact-link@v1
        with:
          token: ${{ github.token }}